### ISSUE TITLE
Hierarchical Testing

### ISSUE THREAD

**Issue by Ninahuadiy** [spholmes/F1000_workflow#14]
Hello,

I'm having an issue with the hierarchical testing portion. I've done everything until the "preprocessing" portion. I skipped down to the hierarchical testing part, and I kept receiving this error:
`Error in estimateSizeFactorsForMatrix(counts(object), locfunc = locfunc,  : 
  every gene contains at least one zero, cannot compute log geometric means`

I'm not sure what this means, but when I checked the ps_dds variable, I have this outcome apart from the paper's result:
<img width="495" alt="screen shot 2017-01-01 at 5 16 14 pm" src="https://cloud.githubusercontent.com/assets/10800569/21583430/12f50274-d046-11e6-8a87-8d359de1332f.png">

**Comment by krisrs1128** [comment]
Hmm, this is an issue that comes up in size factor estimation in the DESeq2 model. One solution might be to change the `type` argument, like this
```
ps_dds <- estimateSizeFactors(ps_dds, type = "iterate")
```
At least, this is the approach [here](https://support.bioconductor.org/p/63229/). Let me know if that fixes things for you, I'll take a look independently too.

**Comment by krisrs1128** [comment]
Alright, I tried that approach, but I'm finding it really slow. An alternative might be to input the geometric means manually (also mentioned on that page). So, you can try getting rid of lines 10 - 13 [here](https://github.com/spholmes/F1000_workflow/blob/master/src/hierarchical-test.R) and instead running

```
# geometric mean, set to zero when all coordinates are zero
geo_mean_protected <- function(x) {
  if (all(x == 0)) {
    return (0)
  }
  exp(mean(log(x[x != 0])))
}

geoMeans <- apply(counts(ps_dds), 1, geo_mean_protected)
ps_dds <- estimateSizeFactors(ps_dds, geoMeans = geoMeans)
ps_dds <- estimateDispersions(ps_dds)
abund <- getVarianceStabilizedData(ps_dds)
```

Let me know how it works out.

**Comment by Ninahuadiy** [comment]
Hello!

Thank you for your answer! So I replaced 10-13 with the geometric means, and I received this error
`Error in data.frame (abund = as.vector(aggregateData), type = environments) : arguments imply differing number of rows: 350, 344` when I tried executing `unadj_p <- treePValues(el, abund, sample_data(pslog)$age_binned)`

I'm not very sure by what the error means. I thought the abund and sample_data(pslog)$age_binned had differing rows, but the abund data table contains 389 rows and the sample_data(pslog)$age_binned had 344 entries.

-Nina

**Comment by Ninahuadiy** [comment]
Also, this was my abundance graph produced with geometric means:
![plot-hier](https://cloud.githubusercontent.com/assets/10800569/21601028/96f119aa-d14a-11e6-9136-438fa2d3bef6.jpeg)

**Comment by krisrs1128** [comment]
Hm, try changing `sample_data(pslog)$age_binned` to `sample_data(ps)$age_binned` and let me know if it works. The issue is that, when applying hierarchical testing, each coordinate of the vector giving groups has to correspond to a row of the counts matrix -- the error is thrown because the dimensions aren't matching. I think somehow when we updated the data, we changed `ps` but not `pslog`.

**Comment by Ninahuadiy** [comment]
I received this error in the screenshot. 
<img width="658" alt="screen shot 2017-01-04 at 1 50 32 pm" src="https://cloud.githubusercontent.com/assets/10800569/21656788/1e97492a-d285-11e6-9700-82385a287070.png">

Would it be more helpful if I provided the script I'm using? It's basically the combination of the analysis and hierarchical-test R scripts, but joined.

**Comment by krisrs1128** [comment]
Hm, sure you can send me the R script you're using (kriss1@stanford.edu) and I'll see if I can reproduce it on my setup. Two other thoughts,

1) What version of igraph are you using? I'm using igraph 1.0.1, on R 3.3.0 on a CentOS machine, and the hierarchical test script is working for me.
2) This seems to be an error [that comes up](http://stackoverflow.com/questions/22819258/igraph-error-cannot-create-empty-graph-with-negative-number-of-vertices) when `el` is not numeric. Can you check that this is the case in your script? This is not the [only time](https://lists.nongnu.org/archive/html/igraph-help/2013-05/msg00041.html) it comes up, but it seems like something worth checking.

**Comment by Ninahuadiy** [comment]
I'm also using igraph 1.0.1, but on R. 3.3.2. 
The V1 column of `el` has NA values after inputting `el[, 1] <- el_names[el0[, 1]]` into the console. Then after inputting `el[, 2] <- el_names[as.numeric(el0[, 2])]` there are entries in V2 that are also NA. That could be the issue?

I also had a question regarding interpreting the first two ordination plots. For Figure 10, how did you conclude that the first axis correlated with the library size. I could see why the second axis corresponds to the age bin because of the separation of points. For Figure 11, how did you come to this conclusion: "samples that have larger scores on the second axis have more taxa from Bacteroidetes and one subset of Firmicutes"after the biplot was created?

**Comment by krisrs1128** [comment]
Ah, the NAs are bad. I think you accidentally left out the `short_names` on line 37 of the hierarchical-test.R script. So, try using
```
el_names <- c(short_names, seq_len(phy_tree(pslog)$Nnode))
```
instead of 
```
el_names <- c(seq_len(phy_tree(pslog)$Nnode))
```
The point is that the `treePValues` function needs to know how to build a tree relating the rows in `abund`. The names in the edgelist need to include the rownames in `abund`, the extra numeric names are for internal nodes that aren't in the `abund` matrix. Let me know if this fixes things.

For Figure 10, I think the association was found separately from the figure. @jfukuyama probably found this by plotting the first axes scores against library size. For Figure 11, the interpretation comes from comparing it with Figure 12 and applying the usual biplot interpretation (sample points are a weighted average of bacteria points, with larger weights for bacteria that are closer to them in the biplot).

**Comment by Ninahuadiy** [comment]
Thanks for pointing that out! It fixed everything. However, I received slightly different results from the paper. I have 473 discoveries and 226 tip discoveries. The parent-child relationships of the plot are also altered. But it looks like "Lachnospiraceae" still predominates.

**Comment by krisrs1128** [comment]
This difference in results is expected, because we had to [change our data source](https://github.com/spholmes/F1000_workflow/commit/5ca3297b1448882ef2179b5d50b7256b3147cd14) after having published the paper.

Thanks for pointing out and being patient with these errors, it helps us keep our code up to date.
