### ISSUE TITLE
Is "http://www.mothur.org" currently down?

### ISSUE THREAD

**Issue by tahirali-biomics** [spholmes/F1000_workflow#23]
I am trying to download "MiSeqDevelopmentData"
from http://www.mothur.org, however, the website is currently down. Is there any other place to download this dataset? Thank you in advance.

**Comment by tahirali-biomics** [comment]
Error message is as under:
trying URL 'http://www.mothur.org/MiSeqDevelopmentData/StabilityNoMetaG.tar'
Error in download.file("http://www.mothur.org/MiSeqDevelopmentData/StabilityNoMetaG.tar",  : 
  cannot open URL 'http://www.mothur.org/MiSeqDevelopmentData/StabilityNoMetaG.tar'
In addition: Warning message:
In download.file("http://www.mothur.org/MiSeqDevelopmentData/StabilityNoMetaG.tar",  :
  InternetOpenUrl failed: 'A connection with the server could not be established'

**Comment by benjjneb** [comment]
There are occasional outages at mothur.org but they do a good job maintaining their online resources over there and I would expect it to be back up in the next couple days. If it isn't we could perhaps set something up temporarily, but we'd rather point to the mothur site rather than rehosting the data ourselves, especially since the mothur team are the folks who generated that dataset.

**Comment by tahirali-biomics** [comment]
Thank you for your quick response to my message. Sure, I can wait a couple of days and give it another try later.

**Comment by benjjneb** [comment]
Looks like mothur.org is back up so you should be able to download this now.

**Comment by tahirali-biomics** [comment]
Yes, it is! Thank you for your help.
